### ISSUE TITLE
PYSPARK_PIN_THREAD error

### ISSUE THREAD

**Issue by S-C-H** [joblib/joblib-spark#11]
Hi,

I'm receiving the following error when attempting a grid search in parallel:

**because pyspark py4j is not in pinned thread mode, we could not terminate running spark jobs correctly.**

The tasks complete but nothing returns!!

I attempted to put it into Pinned Thread Mode using os.environ["PYSPARK_PIN_THREAD"] = "true"
But this does not fix the issue.

**Comment by ace-gabriel** [comment]
Same problem here..did you solve this?

**Comment by S-C-H** [comment]
I did not =(

**Comment by ace-gabriel** [comment]
Yea I think I would probably using 'Threading' and see if it gives similar performance...

**Comment by WeichenXu123** [comment]
@S-C-H Could you paste a minimal code to reproduce your issue ? Thanks!

"because pyspark py4j is not in pinned thread mode, we could not terminate running spark jobs correctly." :  Note that if all jobs finished correctly, this issue will affect nothing.

**Comment by WeichenXu123** [comment]
We remove PIN_THREAD mode now.
See PR https://github.com/joblib/joblib-spark/pull/17
