### ISSUE TITLE
Setting n_jobs parameter correctly

### ISSUE THREAD

**Issue by alexHeu** [joblib/joblib-spark#12]
Hi,

currently I am experimenting with joblib-spark within Databricks to perform distributed hyper-parameter tuning for a LightGBM model.

My cluster consists of 4 worker nodes with 16CPUs each.
LightGBM supports setting an n_jobs parameter (https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor), therefore I am not quite sure how to best set n_jobs in the spark parallel_backend and how these two parameters have influence on each other.
My goal would be to have 4 parallel parameter runs (on the 4 nodes) and each run having available all 16 CPUs to train the model. What kind of configurations do I need to accomplish this?

Thanks in advance
Alex

**Comment by WeichenXu123** [comment]
@alexHeu 
You need to set spark cluster config before spark cluster launch.
```
spark.task.cpus=16
```
then each spark task will request 16 cpu cores. And then you can use joblib-spark and set n_jobs to be 4, Then it should works.
