### ISSUE TITLE
would work with pyspark>=2.4.0 ?

### ISSUE THREAD

**Issue by n1tk** [joblib/joblib-spark#14]
CDH uses `pyspark>=2.4.0, `would work `joblib-spark `with this pyspark version or is hard required `pyspark>=2.4.4` ? 

> What makes the incompatibility ?

**Comment by WeichenXu123** [comment]
@n1tk Will work with version 2.4.0 . I can update the dependency.

**Comment by n1tk** [comment]
Perfect. Please let me know once is updated dependency and will give a try on the cluster to validate. Thank you.

**Comment by WeichenXu123** [comment]
@n1tk https://github.com/joblib/joblib-spark/pull/20
