### ISSUE TITLE
ModuleNotFoundError: No module named 'sklearn.svm._classes'

### ISSUE THREAD

**Issue by kkumawat25** [joblib/joblib-spark#18]
'''from sklearn.utils import parallel_backend
from sklearn.model_selection import cross_val_score
from sklearn import datasets
from sklearn import svm
from joblibspark import register_spark

register_spark() # register spark backend

iris = datasets.load_iris()
clf = svm.SVC(kernel='linear', C=1)
with parallel_backend('spark', n_jobs=3):
  scores = cross_val_score(clf, iris.data, iris.target, cv=5)

print(scores)'''

Above example throws : ModuleNotFoundError: No module named 'sklearn.svm._classes'

**Comment by WeichenXu123** [comment]
@kkumawat25 This is not an issue in joblib-spark code.
I guess you may install different version sklearn in pyspark driver and executor process.
Check first whether your spark driver and executor launch the same version python and install the same version sklearn.
