### ISSUE TITLE
Py4JSecurityException in training

### ISSUE THREAD

**Issue by bxing2000** [joblib/joblib-spark#26]
I have spark runtime 7.2 and sklearn version 0.32.2.

**Run the following sample codes for parallel training:**

register_spark() # register spark backend

iris = datasets.load_iris()
clf = svm.SVC(kernel='linear', C=1)
with parallel_backend('spark', n_jobs=3):
  scores = cross_val_score(clf, iris.data, iris.target, cv=5)

**It resulted in the following error:**

py4j.security.Py4JSecurityException: Method public int org.apache.spark.SparkContext.maxNumConcurrentTasks() is not whitelisted on class class org.apache.spark.SparkContext

Py4JError                                 Traceback (most recent call last)
<command-4101097221978697> in <module>
     10 clf = svm.SVC(kernel='linear', C=1)
     11 with parallel_backend('spark', n_jobs=3):
---> 12   scores = cross_val_score(clf, iris.data, iris.target, cv=5)
     13 
     14 print(scores)

/databricks/python/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

/databricks/python/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in cross_val_score(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, error_score)
    404                                 fit_params=fit_params,
    405                                 pre_dispatch=pre_dispatch,
--> 406                                 error_score=error_score)
    407     return cv_results['test_score']

**Comment by WeichenXu123** [comment]
It has been addressed in newer version databricks runtime.
