### ISSUE TITLE
Publish version 0.1 to PyPI

### ISSUE THREAD

**Issue by mengxr** [joblib/joblib-spark#3]

**Comment by WeichenXu123** [comment]
Released here https://test.pypi.org/project/joblibspark/0.1.0/

**Comment by mengxr** [comment]
@WeichenXu123 you should publish release to pypi.org. test.pypi.org is for testing.

**Comment by WeichenXu123** [comment]
Released here https://pypi.org/project/joblibspark/0.1.0/
