### ISSUE TITLE
prevent jobs from piling up on one node

### ISSUE THREAD

**Issue by pauljohn32** [joblib/joblib-spark#34]
I asked this on StackOverflow. https://stackoverflow.com/q/69051564/1086346

In Databricks, I have several executor nodes, but when I send work out, it is not evenly distributed.  I have tried this many ways, with or without context manager, still have problem.  I expected `batch_size=1` would prevent this from happening.  Spark UI shows example with 4 jobs but there are 2 sent to  one node

![image](https://user-images.githubusercontent.com/344033/132096759-5a2c098f-539d-4441-83db-e6b6d8dd9ea1.png)

Example function call:

```
    from joblib import Parallel, delayed
    from joblibspark import register_spark
        
    register_spark()
        
    output = Parallel(backend="spark", n_jobs=6,
             verbose=config.JOBLIB_VERBOSE, batch_size=1)(
             delayed(fit_one)
             (x, model_data=model_data, dlmodel=dlmodel,
             outdir=outdir,  frac=sample_p,
             score_type=score_type,
             save=save,
             verbose=verbose) for x in ZZ)
```

**Comment by WeichenXu123** [comment]
This might related to spark internal scheduler. You can file databricks ES ticket for help.

**Comment by pauljohn32** [comment]
We updated to newer Databricks version and this problem is much less severe. Am closing here.
