### ISSUE TITLE
Support for dynamic allocation

### ISSUE THREAD

**Issue by peay** [joblib/joblib-spark#7]
This is a great package, but I have been struggling a bit in a context where dynamic allocation of executors is used.

Currently, `n_jobs` cannot be set to a value beyond `spark.maxNumConcurrentTasks`. However, with dynamic allocation:

- There may be no active executors, which prevents the computation from even starting.
- Even if there are executors active, Spark may be configured to allocate more if tasks are pending.

Is there a specific reason not to allow `n_jobs > spark.maxNumConcurrentTasks`, or could we consider relaxing this in the library?

**Comment by mengxr** [comment]
Shall we always set the thread pool size to `n_jobs` but throws a warning if current `spark.maxNumConcurrenttaks` is smaller than `n_jobs`, instead of disallowing it? cc: @WeichenXu123

**Comment by WeichenXu123** [comment]
@mengxr The idea is good. @peay What do you think ?

**Comment by peay** [comment]
That would sound good indeed.
